// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpobr2QXgba3_Q8c3PKl9cBqg5TePB1iw',
    appId: '1:839893065184:web:bd37c473a01646e8609f85',
    messagingSenderId: '839893065184',
    projectId: 'foodfast-965db',
    authDomain: 'foodfast-965db.firebaseapp.com',
    storageBucket: 'foodfast-965db.appspot.com',
    measurementId: 'G-N89HWGMNX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi3pIeTpKh6XlMZSxdd_bAOaeQgVRD1r8',
    appId: '1:839893065184:android:f2e8785d605ec3d0609f85',
    messagingSenderId: '839893065184',
    projectId: 'foodfast-965db',
    storageBucket: 'foodfast-965db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBACwU_pfFWpr9rkqUo3qFluWuq9MfcmSw',
    appId: '1:839893065184:ios:37c29de54e277017609f85',
    messagingSenderId: '839893065184',
    projectId: 'foodfast-965db',
    storageBucket: 'foodfast-965db.appspot.com',
    iosClientId: '839893065184-l4kn5r0j14lilhuc3gujvvtd6dlmdt1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBACwU_pfFWpr9rkqUo3qFluWuq9MfcmSw',
    appId: '1:839893065184:ios:37c29de54e277017609f85',
    messagingSenderId: '839893065184',
    projectId: 'foodfast-965db',
    storageBucket: 'foodfast-965db.appspot.com',
    iosClientId: '839893065184-l4kn5r0j14lilhuc3gujvvtd6dlmdt1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );
}
